name: Build hi for Windows

on:
  workflow_call:
    inputs:
      version-number:
        required: true
        type: string
    outputs:
      artifact-name:
        description: "The name of the produced artifact, possibly containing multiple binaries"
        value: "hi-windows-amd64 hi-windows-386"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64", "386"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
            #cache: true
      - name: Build x64
        env:
          GOARCH: ${{ matrix.arch }}
        run: go build -o "hi-v${{ inputs.version-number }}-${{ matrix.arch }}.exe" ./cmd/hi
      - uses: actions/upload-artifact@v3
        with:
          name: hi-windows-${{ matrix.arch }}
          path: ./*.exe
