name: Build hi

on:
  workflow_call:
    inputs:
      version-number:
        required: true
        type: string
      os-name:
        required: true
        type: string
      os-version:
        required: true
        type: string
      arch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version-number:
        required: true
        type: string
      os-name:
        required: true
        type: string
      os-version:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  artifact-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.artifact-tag.outputs.tag }}
    steps:
      - name: Generate artifact tag
        id: artifact-tag
        run: |
          os_tag=${{ inputs.os-name }}
          if [ "${{ inputs.os-version }}" != "latest" ]
          then
            os_tag=$os_tag-${{ inputs.os-version }}
          fi

          echo "tag=$os_tag-${{ inputs.arch }}" >> $GITHUB_OUTPUT

  build:
    needs: artifact-tag
    runs-on: ${{ inputs.os-name }}-${{ inputs.os-version }}
    defaults:
      text:
        windows:
          "386": "windows-x86"
          amd64: "windows-x64"
        macos:
          "386": "macos-x86"
          amd64: "macos-x64"
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo 'Test: ${{ defaults.text[inputs.os-name][inputs.arch] }}'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
            #cache: true
      - name: Build
        id: build
        env:
          GOARCH: ${{ inputs.arch }}
        run: |
          mkdir bin
          go build -o "bin/hi-v${{ inputs.version-number }}-${{ needs.artifact-tag.outputs.tag }}.exe" ./cmd/hi
      - uses: actions/upload-artifact@v3
        with:
          name: hi-${{ needs.artifact-tag.outputs.tag }}
          path: ./bin/*
