name: Dispatch relevant publish workflow

on:
  release:
    types: [published]

jobs:
  latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latest-tag.outputs.tag }}
      project: ${{ steps.breakdown.outputs.project }}
      version-number: ${{ steps.breakdown.outputs.vernum }}
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Tag breakdown
        id: breakdown
        run: |
          project=$(echo ${{ steps.latest-tag.outputs.tag }} | grep -o '^[^0-9]\+')
          vernum=$(echo ${{ steps.latest-tag.outputs.tag }} | grep -o '[0-9.]\+$')
          echo "project=$project" >> $GITHUB_OUTPUT
          echo "vernum=$vernum" >> $GITHUB_OUTPUT

  hi:
    needs: latest-tag
    if: ${{ needs.latest-tag.outputs.project == 'hi' }}
    uses: ./.github/workflows/release_hi.yml
    with:
      version-number: ${{ needs.latest-tag.outputs.version-number }}
    secrets: inherit
