name: Release hi

on:
  workflow_call:
    inputs:
      version-number:
        required: true
        type: string

jobs:
  windows-x64:
    uses: ./.github/workflows/build_hi_generic.yml
    with:
      version-number: ${{ inputs.version-number }}
      os-name: windows
      os-version: latest
      arch: "amd64"

  windows-x86:
    uses: ./.github/workflows/build_hi_generic.yml
    with:
      version-number: ${{ inputs.version-number }}
      os-name: windows
      os-version: latest
      arch: "386"

  ubuntu-20.04:
    uses: ./.github/workflows/build_hi_generic.yml
    with:
      version-number: ${{ inputs.version-number }}
      os-name: ubuntu
      os-version: "20.04"
      arch: "amd64"

  upload:
    needs: [windows-x64, windows-x86, ubuntu-20.04]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Glob artifacts
        uses: tj-actions/glob@v16
        id: glob
        with:
          files: |
            artifacts/*/*
      - name: Move binaries out of artifact directories
        run: |
          mkdir bin
          mv ${{ steps.glob.outputs.paths }} bin

      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: bin/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
